description: |
  Sense_based Sentiment Analyzer

url: "https://github.com/cjhutto/vaderSentiment"

lang: en

flags: 
 - 'NO'
 - 'BUT'
 - 'LEAST'

lexicons:
 - 'sensitive.tsv'

boosters:
 - 'wnboosters.tsv'

negators:
 - 'wnnegators.tsv'



citation: |
  Hutto, C.J. & Gilbert, E.E. (2014).
  VADER: A Parsimonious Rule-based Model for Sentiment Analysis of Social Media Text.
  Eighth International Conference on Weblogs and Social Media (ICWSM-14). 
  Ann Arbor, MI, June 2014.

citation_url: "https://www.aaai.org/ocs/index.php/ICWSM/ICWSM14/paper/viewFile/8109/8122"
